### ISSUE TITLE
Error on importing local package

### ISSUE THREAD

**Issue by sambaylus** [YoYoGames/GMEXT-Twitch#1]
### Description

I downloaded the .yymp and imported it into a new project.
![image](https://github.com/user-attachments/assets/518debaf-415f-4398-a85e-b0300c159e2e)

### Expected Change

It shouldn't error at import

### Steps To Reproduce

1. Start GameMaker
2. Import the .yymps under "Import Local Package"
3. Error

Output:
Feather finished analyzing project in 211ms
""  

elapsed time 00:00:05.4746499s for command "C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2024.8.1.218/bin/projecttool/windows/x64/ProjectTool.exe" PROJECT SAVE SOURCE="C:\Users\samba\OneDrive\Desktop\Projects\Game Development\Packages\Twitch.Ext.v0.0.1.yymps" DESTINATION="C:\Users\samba\AppData\Local\GameMakerStudio2\GMS2TEMP\Twitch.Ext.v0.0.1_07459d67\extract\Twitch.yyp" started at 09/21/2024 06:25:25
""  

elapsed time 00:00:01.6072577s for command "C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2024.8.1.218/bin/projecttool/windows/x64/ProjectTool.exe" PROJECT SAVE SOURCE="C:\Users\samba\OneDrive\Desktop\Projects\Game Development\Packages\Twitch.Ext.v0.0.1.yymps" DESTINATION="C:\Users\samba\AppData\Local\GameMakerStudio2\GMS2TEMP\Twitch.Ext.v0.0.1_7b07905c\extract\Twitch.yyp" started at 09/21/2024 06:25:42

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Monthly

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by DiasFranciscoA** [comment]
This should be fixed in new 1.0.0 release.
If this is still a problem please open a new issue.
